services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MARIADB_USER: example
      MARIADB_DATABASE: example
      MARIADB_PASSWORD: secret
    restart: always
